name: calendar_heating
channels:
  - conda-forge
dependencies:
  - python=3.10
  - requests
  - icalendar
  - pyyaml
  - python-dotenv
  - pip
  - pip:
      - git+https://github.com/BadPirate/flair-api-client-py.git