name: calendar_heating
channels:
  - defaults
dependencies:
  - python=3.10
  - requests
  - icalendar
  - pyyaml
  - pip
  - python-dotenv
  - pip:
      - git+https://github.com/flair-systems/flair-api-client-py.git
