name: Run AutoFlair daily

on:
  schedule:
    - cron: '0 18 * * *' # 11 AM Pacific Time (18:00 UTC)
  workflow_dispatch:

jobs:
  run-autoflair:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache conda dependencies
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Install Miniconda and Create Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        environment-file: environment.yml
        activate-environment: calendar_heating
        use-mamba: true  # Optional: Faster dependency resolution

    - name: Verify Environment
      run: |
        conda list
        python --version

    - name: Run AutoFlair script
      env:
        ICAL_URL: ${{ secrets.ICAL_URL || '' }} # AirBNB Calendar URL
        FLAIR_CLIENT_ID: ${{ secrets.FLAIR_CLIENT_ID }} # oauth v1 client
        FLAIR_CLIENT_SECRET: ${{ secrets.FLAIR_CLIENT_SECRET }} # oauth v1 secret
        AWAY_TEMP_C: ${{ secrets.AWAY_TEMP_C }} # Optional, default 10C (50F)
        OCCUPIED_TEMP_C: ${{ secrets.OCCUPIED_TEMP_C }}  # Optional, default 18.34C (65F)
      run: |
        conda init
        conda activate calendar_heating
        python AutoFlair.py